package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/rshade/finfocus-plugin-aws-public/internal/regionsconfig"
)

// TestGenerateGoReleaserConfig verifies the GoReleaser configuration generation.
//
// This test validates:
//   - File is created at the specified output path
//   - Region-specific build blocks are generated correctly
//   - Critical build settings (main path, CGO, goos/goarch, ldflags) are present
//   - GoReleaser version and archive configuration are included
func TestGenerateGoReleaserConfig(t *testing.T) {
	tmpDir := t.TempDir()
	outputPath := filepath.Join(tmpDir, ".goreleaser.yaml")

	regions := []regionsconfig.RegionConfig{
		{
			ID:   "use1",
			Name: "us-east-1",
			Tag:  "region_use1",
		},
		{
			ID:   "euw1",
			Name: "eu-west-1",
			Tag:  "region_euw1",
		},
	}

	err := generateGoReleaserConfig(regions, outputPath)
	if err != nil {
		t.Fatalf("generateGoReleaserConfig() error = %v", err)
	}

	// Verify file exists and content
	contentBytes, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Failed to read generated file: %v", err)
	}
	content := string(contentBytes)

	// Region-specific build configuration
	expectedStrings := []string{
		"binary: finfocus-plugin-aws-public-us-east-1",
		"tags:\n      - region_use1",
		"binary: finfocus-plugin-aws-public-eu-west-1",
		"tags:\n      - region_euw1",
		"version: 2",
	}

	// Critical build settings that must be present
	buildSettings := []string{
		"main: ./cmd/finfocus-plugin-aws-public",
		"CGO_ENABLED=0",
		"- linux",
		"- darwin",
		"- windows",
		"- amd64",
		"- arm64",
		"-X main.version=",
	}

	// File structure markers
	structureMarkers := []string{
		"# Generated by tools/generate-goreleaser",
		"builds:",
		"archives:",
		"checksum:",
		"changelog:",
	}

	for _, want := range expectedStrings {
		if !strings.Contains(content, want) {
			t.Errorf("Generated file missing region content %q", want)
		}
	}

	for _, want := range buildSettings {
		if !strings.Contains(content, want) {
			t.Errorf("Generated file missing build setting %q", want)
		}
	}

	for _, want := range structureMarkers {
		if !strings.Contains(content, want) {
			t.Errorf("Generated file missing structure marker %q", want)
		}
	}
}

func TestGenerateGoReleaserConfig_Errors(t *testing.T) {
	// Test case: Output path is a directory, not a file - os.Create will fail
	tmpDir := t.TempDir()
	outputPath := filepath.Join(tmpDir, "collision")
	if err := os.Mkdir(outputPath, 0755); err != nil {
		t.Fatal(err)
	}

	regions := []regionsconfig.RegionConfig{{ID: "use1", Name: "us-east-1", Tag: "region_use1"}}
	
	err := generateGoReleaserConfig(regions, outputPath)
	if err == nil {
		t.Error("generateGoReleaserConfig() expected error when output path is a directory, got nil")
	}
}
